### ISSUE TITLE
Remove spaceMargin prop

### ISSUE THREAD

**Issue by track0x1** [ambistudio/react-native-spacer#4]
Hey,
Just came across this code and I can see great use cases for it. (Like when trying to use a KeyboardAvoidingView inside a component that displays a react-navigation TabNavigator.)

Just looking at the code, we can clean it up by removing the spaceMargin prop and let the user handle that with margin on their own component being rendered inside Spacer.

**Comment by hieunc229** [comment]
Hey @track0x1, thanks for your thoughts. Let users handle the margin would definitely clear up a bit.

Unless it causes a problem, then it would need to be updated. It doesn't make much difference using either of the methods. Since I needed the margin setting quite often, it'd be more convenient to have the margin setting available
